services:
    profilarr:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: profilarr
        ports:
            - 6870:6868
        volumes:
            - ./config-test:/config
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK=002
            - TZ=Australia/Adelaide
        restart: unless-stopped
